### ISSUE TITLE
Crashing on Windows 11

### ISSUE THREAD

**Issue by MathiasDuus** [MathiasDuus/oto#2]
**Describe the bug**
When starting the actual clicking it crashes.

**Additional context**
Windows event handler log:
.NET Version: 6.0.21
Description: The process was terminated due to an unhandled exception.
Exception Info: System.EntryPointNotFoundException: Unable to find an entry point named 'mouseEvent' in DLL 'user32.dll'.
   at oto.AutoClicker.mouseEvent(UInt32 dwFlags, UInt32 dx, UInt32 dy, UInt32 cButtons, UInt32 dwExtraInfo)
   at oto.AutoClicker.AutoClick()
   at System.Threading.Thread.StartCallback()

**Comment by SchultzenDK** [comment]
Please fix this! I beg you! Surely, you're not doing something much more important right now, like your [SVENDEPRØVE] or something like that.

I need it to spend a lot of money on Lotto. I'll be a millionair!! Watch me!! http://www.lotto-simulator.dk

**Comment by MathiasDuus** [comment]
For the time being the exe file available at https://sourceforge.net/projects/oto-the-autoclicker/ can be used.

**Comment by MathiasDuus** [comment]
This has now been fixed

**Comment by SchultzenDK** [comment]
Yoo that's hella gangnam style dude!
